version: '3'
services:
  php_apache:
    container_name: php_apache
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./src:/var/www/html
        - ./php/apache/sites:/etc/apache2/sites-enabled
        - ./php/apache/logs:/var/log/apache2
        - ./php/apache/certs:/etc/ssl/crt
    build: ./php

  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/dump:/docker-entrypoint-initdb.d

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql:db
    ports:
      - 8183:80
    environment:
      MYSQL_ROOT_PASSWORD: 123456
